name: CI

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    # Cypress Docker image with Chrome v78
    # and Firefox v70 pre-installed
    container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: install
        run: yarn install
      
      - name: build
        run: yarn build
      
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:5002'
        env: 
          NODE_ENV: production
          JWT_EXPIRATION_MS: ${{ secrets.JWT_EXPIRATION_MS }}
          MONGO_CS: ${{ secrets.MONGO_CS }} 
          SECRET: ${{ secrets.SECRET }}
        


