name: cypress-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # - name: install
      #   run: yarn

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: yarn run build
          start: yarn run start
          wait-on: http://localhost:5002
        env:
          NODE_ENV: production
          JWT_EXPIRATION_MS: ${{ secrets.JWT_EXPIRATION_MS }}
          MONGO_CS: ${{ secrets.MONGO_CS }}
          SECRET: ${{ secrets.SECRET }}
